export enum AuthErrorCode {
    EMAIL_ALREADY_EXISTS = 'AUTH.EMAIL_ALREADY_EXISTS',
    USERNAME_ALREADY_EXISTS = 'AUTH.USERNAME_ALREADY_EXISTS',
    INVALID_EMAIL = 'AUTH.INVALID_EMAIL',
    INVALID_USERNAME = 'AUTH.INVALID_USERNAME',
    PASSWORD_IS_WEAK = 'AUTH.PASSWORD_IS_WEAK',
    INVALID_PASSWORDHASH = 'AUTH.INVALID_PASSWORDHASH',
    NOT_USABLE_VERIFICATION_TOKEN = 'AUTH.NOT_USABLE_VERIFICATION_TOKEN',
}
