export const SharedErrorCodes = {
    VALIDATION_FAILED: 'SHARED.VALIDATION_FAILED',
    RESOURCE_NOT_FOUND: 'SHARED.RESOURCE_NOT_FOUND',
    UNEXPECTED_ERROR: 'SHARED.UNEXPECTED_ERROR',
    DATABASE_ERROR: 'SHARED.DATABASE_ERROR',
    EXTERNAL_SERVICE_ERROR: 'SHARED.EXTERNAL_SERVICE_ERROR',
    AUTHORIZATION_PERMISSION_DENIED: 'SHARED.AUTHORIZATION.PERMISSION_DENIED',
} as const;
