export const ROLE_REPOSITORY = Symbol('ROLE_REPOSITORY');
export const PERMISSION_REPOSITORY = Symbol('PERMISSION_REPOSITORY');
export const USER_SCHOOL_ROLE_REPOSITORY = Symbol('USER_SCHOOL_ROLE_REPOSITORY');
